### PR TITLE
Update binary_sensor.py

### PR DESCRIPTION
**Pull request by Malaga82**
fix for Detected I/O inside the event loop logs

### CODE REVIEW

**Comment by Malaga82** [comment]
I'm testing this, but should be enough for this custom component.

**Comment by caiosweet** [comment]
Thank you for your time, I think I have solved the problem  for Blocking I/O messages in HA 0.109
[Pre-release](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/releases/tag/v1.2.0)

**Comment by caiosweet** [comment]
Fixed in [v1.2.1](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/releases/tag/v1.2.1)

**Comment by caiosweet** [comment]
Hi, here is the solution with hass.async_add_executor_job ()
Just for knowledge. Thanks for the info.

[v1.1.0](https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/blob/1.1.0/custom_components/dpc/binary_sensor.py) with hass.async_add_executor_job ()

**Pull request closed without merging**
